version: '3.1'

services:

  db:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: openmrs
      MYSQL_DATABASE: openmrs

  openmrs:
    build: .
    image: beapen/openmrs-dev
    command: sleep infinity
    depends_on:
      - db

