name: Build and package

on:
  push:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 8
      uses: actions/setup-java@v2.1.0
      with:
        distribution: 'adopt'
        java-version: 8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Make the compiled omod available
      uses: actions/upload-artifact@v2
      with:
        name: openmrs-module-opspost omod
        path: omod/target/*.omod
        retention-days: 3
