name: Build and package

on:
  push:
    branches: [ master, develop ]

jobs:
  build:
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
        java-version: [ 8 ]
    runs-on: ${{ matrix.platform }}
    env:
      PLATFORM: ${{ matrix.platform }}
      JAVA_VERSION: ${{ matrix.java-version }}
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 8
      uses: actions/setup-java@v2.1.0
      with:
        distribution: 'adopt'
        java-version: ${{ matrix.java-version }}
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Install dependencies
      run: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true --batch-mode --show-version --file pom.xml
    - name: Make the compiled omod available
      uses: actions/upload-artifact@v2
      with:
        name: openmrs-module-opspost omod
        path: omod/target/*.omod
        retention-days: 3
