name: Test on PR

on:
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 8
      uses: actions/setup-java@v2.1.0
      with:
        distribution: 'adopt'
        java-version: 8
    - name: Test with Maven
      run: mvn -B test --file pom.xml

